on:
  push:
    paths:
      - 'geolocation/**'
    branches: [with_mock]

name: Release geolocation

defaults:
  run:
    working-directory: ./geolocation

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create release
        uses: ncipollo/release-action@v1
